update 1password cli usage in backup

diff --git a/scripts/identities-backup b/scripts/identities-backup
--- a/scripts/identities-backup
+++ b/scripts/identities-backup
@@ -1,20 +1,20 @@
 
 #!/usr/bin/env bash
 set -e
-
+echo ${COLUMNS:-80};
 eval 'SESSION=(${!'"OP_SESSION_"'@})'
 if [[ -z $SESSION ]]; then 
-    echo "Login required: eval \$(op signin accountname)"
-    exit 1;
-fi
-
-if ! command -v jq &> /dev/null; then
-    echo "jq command missing."
+    echo "Login required: eval \$(op signin)"
     exit 1;
 fi
 
 if ! command -v base64 &> /dev/null; then
     echo "base64 command missing."
+    exit 1;
+fi
+
+if ! command -v gpg &> /dev/null; then
+    echo "gpg is missing"
     exit 1;
 fi
 
@@ -24,40 +24,27 @@ if ! command -v op &> /dev/null; then
     exit 1;
 fi
 
-function create_note {
-    local TEMPLATE=$(op get template "Secure Note");
-    local JSON=$(echo $TEMPLATE | jq --arg data "$1" '.notesPlain = $data')
-    local ITEM=$(echo $JSON | op encode)
-    local ID=$(op create item 'Secure Note' "$ITEM" --title="$2" | jq -r '.uuid')
-    echo $ID
+function create {
+    echo '';
+    # remove --dry-run to make a backup
+    op item create "$@" --dry-run | cut -c "-${COLUMNS:-80}"
 }
 
 function create_gpg_item {
-    local TEMPLATE=$(op get template "password");
-    local JSON=$(echo $TEMPLATE | jq --arg private "$1" '{k: "concealed", n: "private", t: "Private Key", v: $private} as $p | {name: "", fields: [$p]} as $section | .password = "" | .sections = [$section]')
-    local ITEM=$(echo $JSON | op encode)
-    local ID=$(op create item 'password' "$ITEM" --title="$2" | jq -r '.uuid')
-    echo $ID
+    GPG=$(gpg --export-secret-keys --export-options export-backup --armor | base64);
+    create --category=password "Private Key=$GPG" --title="$1"
 }
 
 function create_ssh_item {
-    local TEMPLATE=$(op get template "password");
-    local JSON=$(echo $TEMPLATE | jq --arg private "$1" --arg public "$2" --arg config "$3" '{k: "concealed", n: "public", t: "Public Key", v: $public} as $p1 | {k: "concealed", n: "private", t: "Private Key", v: $private} as $p2 | {name: "", fields: [$p1,$p2]} as $section | .password = "" | .sections = [$section] | .notesPlain = $config')
-    local ITEM=$(echo $JSON | op encode)
-    local ID=$(op create item 'password' "$ITEM" --title="$4" | jq -r '.uuid')
-    echo $ID;
+    CONFIG=$(cat ~/.ssh/config);
+    PRIVATE=$(cat ~/.ssh/id_rsa | base64);
+    PUBLIC=$(cat ~/.ssh/id_rsa.pub);
+    create --category=password "Private Key=$PRIVATE" "Public Key=$PUBLIC" "notesPlain=$CONFIG" --title="$1"
 }
 
-if command -v gpg &> /dev/null; then
+
 # Backup GPG Identity
-    GPG=$(gpg --export-secret-keys --export-options export-backup --armor | base64);
-    GPG_ID=$(create_gpg_item "$GPG" "gpg-backup")
-else
-    echo "You do not appear to have gpg. skipping."
-fi
+create_gpg_item "gpg-backup"
 
 # Backup SSH Identity
-CONFIG=$(cat ~/.ssh/config);
-PRIVATE=$(cat ~/.ssh/id_rsa | base64);
-PUBLIC=$(cat ~/.ssh/id_rsa.pub);
-SSH_KEYS_ID=$(create_ssh_item "$PRIVATE" "$PUBLIC" "$CONFIG" "ssh-backup")
+create_ssh_item "ssh-backup"
